### ISSUE TITLE
User Update/Delete not working

### ISSUE THREAD

**Issue by tmoon8730** [SCCapstone/AdviseMe#217]
The user service update feature is not reflecting the changes in the db.

**Comment by tmoon8730** [comment]
Also refactor the api to the same way the other apis are run

**Comment by tbhall** [comment]
Error:
/Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/mongo_client.js:804
          throw err;
          ^

TypeError: Cannot read property 'apply' of undefined
    at EventEmitter.<anonymous> (/Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongoskin/lib/collection.js:51:21)
    at Object.onceWrapper (events.js:255:19)
    at EventEmitter.emit (events.js:160:13)
    at /Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongoskin/lib/utils.js:134:27
    at result (/Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/utils.js:413:17)
    at executeCallback (/Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/utils.js:405:9)
    at /Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/mongo_client.js:271:5
    at connectCallback (/Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/mongo_client.js:940:5)
    at /Users/tbhall/SchoolWork/Spring_Senior/AdviseMe/adviseme-api/node_modules/mongodb/lib/mongo_client.js:801:11
    at process._tickCallback (internal/process/next_tick.js:150:11)

**Comment by tbhall** [comment]
Seems to be working in dev... In admin and can update and delete users....
